### ISSUE TITLE
why in hololens2, the entire model is covered by the material instead of the model outline.

### ISSUE THREAD

**Issue by Jing-Fu** [microsoft/MixedReality-GraphicsTools-Unity#219]
MeshOutline use Stencil Outline is true.

<img width="599" alt="螢幕擷取畫面 2024-06-19 143859" src="https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/41951009/0ac90f3b-8eb9-45ce-92c3-19900caecc26">

**Comment by Jing-Fu** [comment]
After my testing, I have to change it to Depth 24 Bit as shown below, so that it will only be displayed in the outline. Can anyone tell me the reason?
<img width="203" alt="image" src="https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/41951009/a892cf3f-3a19-4c2b-93a6-b58fc8ff7674">

**Comment by Cameron-Micka** [comment]
Hi @Jing-Fu, thanks for reporting this! You are correct you need to det the depth buffer to 24 bits when using stencil outlines because stencil outlines require the stencil buffer.  Unity does not create a stencil buffer when using 16-bit depth format. Thus, some stencil-required effects (like Unity UI effects and stencil outlines) will not work unless 24-bit depth format is selected which will create an 8-bit stencil buffer and 16-bit depth buffer. You can find more details here: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/recommended-settings-for-unity?tabs=openxr#enable-depth-buffer-sharing
